/*
	wcfServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "wcfServiceExample.h"
#import "wcfService.h"

@implementation wcfServiceExample

- (void)run {
	// Create the service
	wcfService* service = [wcfService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns BOOL. 
	[service xAddUserLog:self action:@selector(xAddUserLogHandler:) xemail: @"" xpassword: @"" xidcia: @"" logscreen: @"" keyname: @"" filename: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xApproveBustOut:self action:@selector(xApproveBustOutHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidnumber: @"" toemail: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xApproveSuggest:self action:@selector(xApproveSuggestHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" xidproject: @"" xsqft: @"" xsuggestprice: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xAprroveRequestedPOWithEmail:self action:@selector(xAprroveRequestedPOWithEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" reason: @"" xtotal: @"" xdate: @"" xnotes: @"" xstr: @"" emailbody: @"" EquipmentType: @""];

	// Returns wcfUserCOEmail*. 
	[service xChangeOrderGetEmail:self action:@selector(xChangeOrderGetEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xcoid: @"" xtype: @""];

	// Returns wcfKeyValueItem*. 
	[service xCheckApproveSuggest:self action:@selector(xCheckApproveSuggestHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xsqft: @"" xsuggestprice: @""];

	// Returns wcfKeyValueItem*. 
	[service xCheckDisApproveSuggest:self action:@selector(xCheckDisApproveSuggestHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xsqft: @"" xsuggestprice: @""];

	// Returns wcfKeyValueItem*. 
	[service xCheckLogin:self action:@selector(xCheckLoginHandler:) xemail: @"" xpassword: @"" EquipmentType: @""];

	// Returns wcfProjectScheduleComplete*. 
	[service xCompleteSchedule:self action:@selector(xCompleteScheduleHandler:) xemail: @"" xpassword: @"" xidcia: @"" xprojectid: @"" refid: @"" completeDate: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xDeleteSelectionCalendar:self action:@selector(xDeleteSelectionCalendarHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xDisapproveBustOut:self action:@selector(xDisapproveBustOutHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidnumber: @"" toemail: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xDisApproveSuggest:self action:@selector(xDisApproveSuggestHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" xidproject: @"" xsqft: @"" xsuggestprice: @"" xcounterprice: @"" xtext: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xDisAprroveRequestedPOWithEmail:self action:@selector(xDisAprroveRequestedPOWithEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" emailbody: @"" xtotal: @"" xdate: @"" xstr: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xFoundForApprove:self action:@selector(xFoundForApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @""];

	// Returns wcfBustOutItem*. 
	[service xGetBustOutDetailForApprove:self action:@selector(xGetBustOutDetailForApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" xid: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xGetBustOutEmail:self action:@selector(xGetBustOutEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidnumber: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetBustOutListForApprove:self action:@selector(xGetBustOutListForApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetCalendarBuilderForApprove:self action:@selector(xGetCalendarBuilderForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetCalendarBuyerForApprove:self action:@selector(xGetCalendarBuyerForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns wcfCalendarEntryItem*. 
	[service xGetCalendarEntry:self action:@selector(xGetCalendarEntryHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetCiaList:self action:@selector(xGetCiaListHandler:) xemail: @"" xpassword: @"" EquipmentType: @""];

	// Returns wcfCODetail*. 
	[service xGetCODetailForApprove:self action:@selector(xGetCODetailForApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" xcoid: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetCOListForApprove:self action:@selector(xGetCOListForApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns wcfKeyValueItem*. 
	[service xGetContractApproveEmailTo:self action:@selector(xGetContractApproveEmailToHandler:) xemail: @"" xpassword: @"" xidcia: @"" contractid: @""];

	// Returns wcfContractEntryItem*. 
	[service xGetContractEntry:self action:@selector(xGetContractEntryHandler:) xemail: @"" xpassword: @"" xidcia: @"" contractid: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetContractForApprove:self action:@selector(xGetContractForApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetDevelopmentVendorList:self action:@selector(xGetDevelopmentVendorListHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetEmailList:self action:@selector(xGetEmailListHandler:) xemail: @"" xpassword: @"" xidcia: @"" idvendor: @""];

	// Returns NSMutableArray*. 
	[service xGetEmailList2:self action:@selector(xGetEmailList2Handler:) xemail: @"" xpassword: @"" xidcia: @"" xpo1: @"" idvendor: @"" xtype: @""];

	// Returns NSString*. 
	[service xGetEmailListDisapprove:self action:@selector(xGetEmailListDisapproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" poid: @""];

	// Returns NSMutableArray*. 
	[service xGetInspectorByMonthAndEmail:self action:@selector(xGetInspectorByMonthAndEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xyear: @"" xqaemail: @"" xmonth: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetInspectorByYear:self action:@selector(xGetInspectorByYearHandler:) xemail: @"" xpassword: @"" xidcia: @"" xyear: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetKirbyTitleCnt:self action:@selector(xGetKirbyTitleCntHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetKirbyTitleList:self action:@selector(xGetKirbyTitleListHandler:) xemail: @"" xpassword: @"" xidcia: @"" tdate: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetMasterCia:self action:@selector(xGetMasterCiaHandler:) xemail: @"" password: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetMenuBustOutForApprove:self action:@selector(xGetMenuBustOutForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetMenuCOForApprove:self action:@selector(xGetMenuCOForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetMenuContractForApprove:self action:@selector(xGetMenuContractForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetMenuForApprove:self action:@selector(xGetMenuForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetMenuPOForApprove:self action:@selector(xGetMenuPOForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" xtype: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetMenuRequestedPOForApprove:self action:@selector(xGetMenuRequestedPOForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetMenuRequestedPOHold:self action:@selector(xGetMenuRequestedPOHoldHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetNewPoVendorEmail:self action:@selector(xGetNewPoVendorEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidvendor: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetNewSchedule1:self action:@selector(xGetNewSchedule1Handler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetNewSchedule2:self action:@selector(xGetNewSchedule2Handler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xstep: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetPendingVpo:self action:@selector(xGetPendingVpoHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" EquipmentType: @""];

	// Returns wcfvpoDetail*. 
	[service xGetPendingVpoDetail:self action:@selector(xGetPendingVpoDetailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" idvpo: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetPhoneList:self action:@selector(xGetPhoneListHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns wcfPhoneListItem*. 
	[service xGetPhoneListEntry:self action:@selector(xGetPhoneListEntryHandler:) xemail: @"" xpassword: @"" xidcia: @"" xemail1: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetPO93:self action:@selector(xGetPO93Handler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" idvendor: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetPO93list:self action:@selector(xGetPO93listHandler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" idvendor: @"" xstatus: @"" currentPage: 0 EquipmentType: @""];

	// Returns wcfPODetail*. 
	[service xGetPODetail:self action:@selector(xGetPODetailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xpoid: @"" xcode: @"" EquipmentType: @""];

	// Returns wcfPODetail*. 
	[service xGetPODetailForSubmit:self action:@selector(xGetPODetailForSubmitHandler:) xemail: @"" xpassword: @"" xidcia: @"" xpoid: @"" xvendorid: @"" xcode: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetPOForApproveList:self action:@selector(xGetPOForApproveListHandler:) xemail: @"" xpassword: @"" xidcia: @"" xtype: @"" currentPage: 0 EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetPoVendor:self action:@selector(xGetPoVendorHandler:) xemail: @"" xpassword: @"" xidcia: @"" currentPage: 0 EquipmentType: @""];

	// Returns wcfProjectItem*. 
	[service xGetProject:self action:@selector(xGetProjectHandler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" xtype: 0 EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetProjectAddendumc:self action:@selector(xGetProjectAddendumcHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetProjectCOList:self action:@selector(xGetProjectCOListHandler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetProjectFiles:self action:@selector(xGetProjectFilesHandler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetProjectPhotoFolder:self action:@selector(xGetProjectPhotoFolderHandler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" xtype: 0 EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetProjectRequestedPOLs:self action:@selector(xGetProjectRequestedPOLsHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetQACalendarCnt:self action:@selector(xGetQACalendarCntHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns wcfCalendarQA*. 
	[service xGetQACalendarEntry:self action:@selector(xGetQACalendarEntryHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" EquipmentType: @""];

	// Returns wcfCalendarQAbItemDetail*. 
	[service xGetQaCalendarInspection2bItem:self action:@selector(xGetQaCalendarInspection2bItemHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetQACalendarList:self action:@selector(xGetQACalendarListHandler:) xemail: @"" xpassword: @"" xidcia: @"" tdate: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xGetQACalendarStatus:self action:@selector(xGetQACalendarStatusHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" EquipmentType: @""];

	// Returns wcfInspectionqa*. 
	[service xGetQAInspection:self action:@selector(xGetQAInspectionHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" EquipmentType: @""];

	// Returns wcfCalendarQAb*. 
	[service xGetQAInspection2b:self action:@selector(xGetQAInspection2bHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetQAInspection2bAdd:self action:@selector(xGetQAInspection2bAddHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetQAInspection2bItemLs:self action:@selector(xGetQAInspection2bItemLsHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" xstatus: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetReasons:self action:@selector(xGetReasonsHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns wcfRequestedPODetail*. 
	[service xGetRequestedPOForApproveDetail:self action:@selector(xGetRequestedPOForApproveDetailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetRequestedPOForApproveLs:self action:@selector(xGetRequestedPOForApproveLsHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetRequestedPOHoldLs:self action:@selector(xGetRequestedPOHoldLsHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xgetRequestedPoReason:self action:@selector(xgetRequestedPoReasonHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetReschedule:self action:@selector(xGetRescheduleHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidmainstep: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetSelectionCalendarCnt:self action:@selector(xGetSelectionCalendarCntHandler:) xemail: @"" xpassword: @"" xidcia: @"" EquipmentType: @""];

	// Returns wcfCalendarEntryItem*. 
	[service xGetSelectionCalendarEntry:self action:@selector(xGetSelectionCalendarEntryHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetSelectionCalendarList:self action:@selector(xGetSelectionCalendarListHandler:) xemail: @"" xpassword: @"" xidcia: @"" tdate: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetStartPackList:self action:@selector(xGetStartPackListHandler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" EquipmentType: @""];

	// Returns wcfSuggestedPriceItem*. 
	[service xGetSuggestedPrice:self action:@selector(xGetSuggestedPriceHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @""];

	// Returns wcfSuggestedPriceItem*. 
	[service xGetSuggestedPriceForApprove:self action:@selector(xGetSuggestedPriceForApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @""];

	// Returns NSMutableArray*. 
	[service xGetSuggestedPricelist:self action:@selector(xGetSuggestedPricelistHandler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" currentPage: 0 EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetSuggestedPricelistForApprove:self action:@selector(xGetSuggestedPricelistForApproveHandler:) xemail: @"" xpassword: @"" mastercompany: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetTaskDue:self action:@selector(xGetTaskDueHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" EquipmentType: @""];

	// Returns wcfUserProfileItem*. 
	[service xGetUserProfile:self action:@selector(xGetUserProfileHandler:) xemail: @"" xpassword: @"" EquipmentType: @""];

	// Returns wcfVendorInfo*. 
	[service xGetVendorInfo:self action:@selector(xGetVendorInfoHandler:) xemail: @"" xpassword: @"" xciaid: @"" xiddevelopment: @"" xvendorid: @"" EquipmentType: @""];

	// Returns wcfVendorInfo*. 
	[service xGetVendorInfo2:self action:@selector(xGetVendorInfo2Handler:) xemail: @"" xpassword: @"" xciaid: @"" xvendorid: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetVendorPOSelectCia:self action:@selector(xGetVendorPOSelectCiaHandler:) xemail: @"" xpassword: @"" mastercompany: @"" idvendor: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetVendors:self action:@selector(xGetVendorsHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidcostcode: @"" projectid: @"" currentPage: 0 EquipmentType: @""];

	// Returns NSString*. 
	[service xHoldRequestedPOWithEmail:self action:@selector(xHoldRequestedPOWithEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" emailbody: @"" xtotal: @"" xdate: @"" xstr: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xisupdate_android:self action:@selector(xisupdate_androidHandler:) version: @""];

	// Returns NSString*. 
	[service xisupdate_ipad:self action:@selector(xisupdate_ipadHandler:) version: @""];

	// Returns NSString*. 
	[service xisupdate_iphone:self action:@selector(xisupdate_iphoneHandler:) version: @""];

	// Returns NSString*. 
	[service xisupdate_tablet:self action:@selector(xisupdate_tabletHandler:) version: @""];

	// Returns NSString*. 
	[service xNewVPO:self action:@selector(xNewVPOHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidvendor: @"" xnvendor: @"" xidreason: @"" xnreason: @"" toemail: @"" delivery: @"" notes: @"" quantity: @"" total: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xNewVPOWithPhoto:self action:@selector(xNewVPOWithPhotoHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidvendor: @"" xnvendor: @"" xidreason: @"" xnreason: @"" toemail: @"" delivery: @"" notes: @"" total: @"" photoBase64String: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bAdd:self action:@selector(xQaCalendarInspection2bAddHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject1chk1: @"" reason: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bAddPass:self action:@selector(xQaCalendarInspection2bAddPassHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject1chk1: @"" reason: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bAddPassWithImg:self action:@selector(xQaCalendarInspection2bAddPassWithImgHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject1chk1: @"" reason: @"" xnotes: @"" photoBase64String: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bAddWithImg:self action:@selector(xQaCalendarInspection2bAddWithImgHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject1chk1: @"" reason: @"" xnotes: @"" photoBase64String: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bBtn3:self action:@selector(xQaCalendarInspection2bBtn3Handler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bBtn3WithImg:self action:@selector(xQaCalendarInspection2bBtn3WithImgHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" photoBase64String: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bBtn4:self action:@selector(xQaCalendarInspection2bBtn4Handler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bBtn4WithImg:self action:@selector(xQaCalendarInspection2bBtn4WithImgHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" photoBase64String: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bUpd:self action:@selector(xQaCalendarInspection2bUpdHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xQaCalendarInspection2bUpdWithImg:self action:@selector(xQaCalendarInspection2bUpdWithImgHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" xnotes: @"" photoBase64String: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xSaveSelectionCalendar:self action:@selector(xSaveSelectionCalendarHandler:) xemail: @"" xpassword: @"" xidcia: @"" calendarData: @"" xidnumber: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xSearchProject:self action:@selector(xSearchProjectHandler:) xemail: @"" xpassword: @"" xidcia: @"" xtype: 0 currentPage: 0 EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xSearchProjects:self action:@selector(xSearchProjectsHandler:) xemail: @"" xpassword: @"" xidcia: @"" keyword: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xSearchVendorList:self action:@selector(xSearchVendorListHandler:) xemail: @"" xpassword: @"" xidcia: @"" keyword: @"" EquipmentType: @""];

	// Returns BOOL. 
	[service xSendEmail:self action:@selector(xSendEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xpoid: @"" xto: @"" oldvendoremail: @"" xmsg: @"" EquipmentType: @"" xtype: @""];

	// Returns NSString*. 
	[service xSendGetPasswordMail:self action:@selector(xSendGetPasswordMailHandler:) xemail: @"" EquipmentType: @""];

	// Returns BOOL. 
	[service xSendMessage:self action:@selector(xSendMessageHandler:) xemail: @"" xpassword: @"" xidcia: @"" xpoid: @"" oldvendoremail: @"" xmsg: @"" EquipmentType: @"" xtype: @""];

	// Returns NSString*. 
	[service xSubmitReschedule:self action:@selector(xSubmitRescheduleHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidmainstep: @"" xidreson: @"" xnreson: @"" xredate: @"" xcomment: @"" xdays: @"" EquipmentType: @""];

	// Returns wcfKeyValueItem*. 
	[service xSubmitSuggestPrice:self action:@selector(xSubmitSuggestPriceHandler:) xemail: @"" xpassword: @"" xidcia: @"" projectid: @"" suggestedPrice: @"" sqft: @"" comment: @"" toemail: @"" EquipmentType: @""];

	// Returns int. 
	[service xUpdateCalendarApprove:self action:@selector(xUpdateCalendarApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" calendarData: @"" xidnumber: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdateCalendarApprove1:self action:@selector(xUpdateCalendarApprove1Handler:) xemail: @"" xpassword: @"" xidcia: @"" calendarData: @"" xidnumber: @"" EquipmentType: @""];

	// Returns int. 
	[service xUpdateCalendarDisApprove:self action:@selector(xUpdateCalendarDisApproveHandler:) xemail: @"" xpassword: @"" xidcia: @"" calendarData: @"" xidnumber: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdateCalendarDisApprove1:self action:@selector(xUpdateCalendarDisApprove1Handler:) xemail: @"" xpassword: @"" xidcia: @"" calendarData: @"" xidnumber: @"" EquipmentType: @""];

	// Returns int. 
	[service xUpdateContract:self action:@selector(xUpdateContractHandler:) xemail: @"" xpassword: @"" xidcia: @"" contractid: @"" xtype: @"" toemail: @"" msg: @"" EquipmentType: @""];

	// Returns int. 
	[service xUpdateUserChangeOrder:self action:@selector(xUpdateUserChangeOrderHandler:) xemail: @"" xpassword: @"" xidcia: @"" xcoid: @"" xtype: @"" toemail: @"" msg: @"" EquipmentType: @""];

	// Returns int. 
	[service xUpdateUserProfile:self action:@selector(xUpdateUserProfileHandler:) xemail: @"" xpassword: @"" title: @"" name: @"" fax: @"" mobile: @"" phone: @"" photoBase64String: @"" EquipmentType: @""];

	// Returns int. 
	[service xUpdateUserProfileWithoutPhoto:self action:@selector(xUpdateUserProfileWithoutPhotoHandler:) xemail: @"" xpassword: @"" title: @"" name: @"" fax: @"" mobile: @"" phone: @"" EquipmentType: @""];

	// Returns int. 
	[service xUpdateUserPurchaseOrder:self action:@selector(xUpdateUserPurchaseOrderHandler:) xemail: @"" xpassword: @"" xidcia: @"" xpoid: @"" xtype: @"" update: @"" vendorid: @"" delivery: @"" xlgsel: @"" xcode: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdateVPO:self action:@selector(xUpdateVPOHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidnumber: @"" toemail: @"" delivery: @"" notes: @"" total: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdateVPOWithPhoto:self action:@selector(xUpdateVPOWithPhotoHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xidnumber: @"" toemail: @"" delivery: @"" notes: @"" total: @"" photoBase64String: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdQANotReady:self action:@selector(xUpdQANotReadyHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdQAReady:self action:@selector(xUpdQAReadyHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdQAResubmit:self action:@selector(xUpdQAResubmitHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdQASaveAndFail:self action:@selector(xUpdQASaveAndFailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUpdQASaveAndFinish:self action:@selector(xUpdQASaveAndFinishHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xUploadPhotos:self action:@selector(xUploadPhotosHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidproject: @"" xFolderid: @"" xFolder1id: @"" xFolder2id: @"" xFolder2Name: @"" fname: @"" ftype: @"" ftags: @"" fileBase64String: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xVoidRequestedPOWithEmail:self action:@selector(xVoidRequestedPOWithEmailHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnum: @"" emailbody: @"" xtotal: @"" xdate: @"" xstr: @"" xnotes: @"" EquipmentType: @""];

	// Returns NSString*. 
	[service xVoidVPO:self action:@selector(xVoidVPOHandler:) xemail: @"" xpassword: @"" xidcia: @"" xidnumber: @"" EquipmentType: @""];
}

	

// Handle the response from xAddUserLog.
		
- (void) xAddUserLogHandler: (BOOL) value {
			

	// Do something with the BOOL result
		
	NSLog(@"xAddUserLog returned the value: %@", [NSNumber numberWithBool:value]);
			
}
	

// Handle the response from xApproveBustOut.
		
- (void) xApproveBustOutHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xApproveBustOut returned the value: %@", result);
			
}
	

// Handle the response from xApproveSuggest.
		
- (void) xApproveSuggestHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xApproveSuggest returned the value: %@", result);
			
}
	

// Handle the response from xAprroveRequestedPOWithEmail.
		
- (void) xAprroveRequestedPOWithEmailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xAprroveRequestedPOWithEmail returned the value: %@", result);
			
}
	

// Handle the response from xChangeOrderGetEmail.
		
- (void) xChangeOrderGetEmailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfUserCOEmail* result
		wcfUserCOEmail* result = (wcfUserCOEmail*)value;
	NSLog(@"xChangeOrderGetEmail returned the value: %@", result);
			
}
	

// Handle the response from xCheckApproveSuggest.
		
- (void) xCheckApproveSuggestHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfKeyValueItem* result
		wcfKeyValueItem* result = (wcfKeyValueItem*)value;
	NSLog(@"xCheckApproveSuggest returned the value: %@", result);
			
}
	

// Handle the response from xCheckDisApproveSuggest.
		
- (void) xCheckDisApproveSuggestHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfKeyValueItem* result
		wcfKeyValueItem* result = (wcfKeyValueItem*)value;
	NSLog(@"xCheckDisApproveSuggest returned the value: %@", result);
			
}
	

// Handle the response from xCheckLogin.
		
- (void) xCheckLoginHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfKeyValueItem* result
		wcfKeyValueItem* result = (wcfKeyValueItem*)value;
	NSLog(@"xCheckLogin returned the value: %@", result);
			
}
	

// Handle the response from xCompleteSchedule.
		
- (void) xCompleteScheduleHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfProjectScheduleComplete* result
		wcfProjectScheduleComplete* result = (wcfProjectScheduleComplete*)value;
	NSLog(@"xCompleteSchedule returned the value: %@", result);
			
}
	

// Handle the response from xDeleteSelectionCalendar.
		
- (void) xDeleteSelectionCalendarHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xDeleteSelectionCalendar returned the value: %@", result);
			
}
	

// Handle the response from xDisapproveBustOut.
		
- (void) xDisapproveBustOutHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xDisapproveBustOut returned the value: %@", result);
			
}
	

// Handle the response from xDisApproveSuggest.
		
- (void) xDisApproveSuggestHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xDisApproveSuggest returned the value: %@", result);
			
}
	

// Handle the response from xDisAprroveRequestedPOWithEmail.
		
- (void) xDisAprroveRequestedPOWithEmailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xDisAprroveRequestedPOWithEmail returned the value: %@", result);
			
}
	

// Handle the response from xFoundForApprove.
		
- (void) xFoundForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xFoundForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetBustOutDetailForApprove.
		
- (void) xGetBustOutDetailForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfBustOutItem* result
		wcfBustOutItem* result = (wcfBustOutItem*)value;
	NSLog(@"xGetBustOutDetailForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetBustOutEmail.
		
- (void) xGetBustOutEmailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xGetBustOutEmail returned the value: %@", result);
			
}
	

// Handle the response from xGetBustOutListForApprove.
		
- (void) xGetBustOutListForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetBustOutListForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetCalendarBuilderForApprove.
		
- (void) xGetCalendarBuilderForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetCalendarBuilderForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetCalendarBuyerForApprove.
		
- (void) xGetCalendarBuyerForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetCalendarBuyerForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetCalendarEntry.
		
- (void) xGetCalendarEntryHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfCalendarEntryItem* result
		wcfCalendarEntryItem* result = (wcfCalendarEntryItem*)value;
	NSLog(@"xGetCalendarEntry returned the value: %@", result);
			
}
	

// Handle the response from xGetCiaList.
		
- (void) xGetCiaListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetCiaList returned the value: %@", result);
			
}
	

// Handle the response from xGetCODetailForApprove.
		
- (void) xGetCODetailForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfCODetail* result
		wcfCODetail* result = (wcfCODetail*)value;
	NSLog(@"xGetCODetailForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetCOListForApprove.
		
- (void) xGetCOListForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetCOListForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetContractApproveEmailTo.
		
- (void) xGetContractApproveEmailToHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfKeyValueItem* result
		wcfKeyValueItem* result = (wcfKeyValueItem*)value;
	NSLog(@"xGetContractApproveEmailTo returned the value: %@", result);
			
}
	

// Handle the response from xGetContractEntry.
		
- (void) xGetContractEntryHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfContractEntryItem* result
		wcfContractEntryItem* result = (wcfContractEntryItem*)value;
	NSLog(@"xGetContractEntry returned the value: %@", result);
			
}
	

// Handle the response from xGetContractForApprove.
		
- (void) xGetContractForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetContractForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetDevelopmentVendorList.
		
- (void) xGetDevelopmentVendorListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetDevelopmentVendorList returned the value: %@", result);
			
}
	

// Handle the response from xGetEmailList.
		
- (void) xGetEmailListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetEmailList returned the value: %@", result);
			
}
	

// Handle the response from xGetEmailList2.
		
- (void) xGetEmailList2Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetEmailList2 returned the value: %@", result);
			
}
	

// Handle the response from xGetEmailListDisapprove.
		
- (void) xGetEmailListDisapproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xGetEmailListDisapprove returned the value: %@", result);
			
}
	

// Handle the response from xGetInspectorByMonthAndEmail.
		
- (void) xGetInspectorByMonthAndEmailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetInspectorByMonthAndEmail returned the value: %@", result);
			
}
	

// Handle the response from xGetInspectorByYear.
		
- (void) xGetInspectorByYearHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetInspectorByYear returned the value: %@", result);
			
}
	

// Handle the response from xGetKirbyTitleCnt.
		
- (void) xGetKirbyTitleCntHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetKirbyTitleCnt returned the value: %@", result);
			
}
	

// Handle the response from xGetKirbyTitleList.
		
- (void) xGetKirbyTitleListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetKirbyTitleList returned the value: %@", result);
			
}
	

// Handle the response from xGetMasterCia.
		
- (void) xGetMasterCiaHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetMasterCia returned the value: %@", result);
			
}
	

// Handle the response from xGetMenuBustOutForApprove.
		
- (void) xGetMenuBustOutForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetMenuBustOutForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetMenuCOForApprove.
		
- (void) xGetMenuCOForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetMenuCOForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetMenuContractForApprove.
		
- (void) xGetMenuContractForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetMenuContractForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetMenuForApprove.
		
- (void) xGetMenuForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetMenuForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetMenuPOForApprove.
		
- (void) xGetMenuPOForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetMenuPOForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetMenuRequestedPOForApprove.
		
- (void) xGetMenuRequestedPOForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetMenuRequestedPOForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetMenuRequestedPOHold.
		
- (void) xGetMenuRequestedPOHoldHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetMenuRequestedPOHold returned the value: %@", result);
			
}
	

// Handle the response from xGetNewPoVendorEmail.
		
- (void) xGetNewPoVendorEmailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetNewPoVendorEmail returned the value: %@", result);
			
}
	

// Handle the response from xGetNewSchedule1.
		
- (void) xGetNewSchedule1Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetNewSchedule1 returned the value: %@", result);
			
}
	

// Handle the response from xGetNewSchedule2.
		
- (void) xGetNewSchedule2Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetNewSchedule2 returned the value: %@", result);
			
}
	

// Handle the response from xGetPendingVpo.
		
- (void) xGetPendingVpoHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetPendingVpo returned the value: %@", result);
			
}
	

// Handle the response from xGetPendingVpoDetail.
		
- (void) xGetPendingVpoDetailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfvpoDetail* result
		wcfvpoDetail* result = (wcfvpoDetail*)value;
	NSLog(@"xGetPendingVpoDetail returned the value: %@", result);
			
}
	

// Handle the response from xGetPhoneList.
		
- (void) xGetPhoneListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetPhoneList returned the value: %@", result);
			
}
	

// Handle the response from xGetPhoneListEntry.
		
- (void) xGetPhoneListEntryHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfPhoneListItem* result
		wcfPhoneListItem* result = (wcfPhoneListItem*)value;
	NSLog(@"xGetPhoneListEntry returned the value: %@", result);
			
}
	

// Handle the response from xGetPO93.
		
- (void) xGetPO93Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetPO93 returned the value: %@", result);
			
}
	

// Handle the response from xGetPO93list.
		
- (void) xGetPO93listHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetPO93list returned the value: %@", result);
			
}
	

// Handle the response from xGetPODetail.
		
- (void) xGetPODetailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfPODetail* result
		wcfPODetail* result = (wcfPODetail*)value;
	NSLog(@"xGetPODetail returned the value: %@", result);
			
}
	

// Handle the response from xGetPODetailForSubmit.
		
- (void) xGetPODetailForSubmitHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfPODetail* result
		wcfPODetail* result = (wcfPODetail*)value;
	NSLog(@"xGetPODetailForSubmit returned the value: %@", result);
			
}
	

// Handle the response from xGetPOForApproveList.
		
- (void) xGetPOForApproveListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetPOForApproveList returned the value: %@", result);
			
}
	

// Handle the response from xGetPoVendor.
		
- (void) xGetPoVendorHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetPoVendor returned the value: %@", result);
			
}
	

// Handle the response from xGetProject.
		
- (void) xGetProjectHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfProjectItem* result
		wcfProjectItem* result = (wcfProjectItem*)value;
	NSLog(@"xGetProject returned the value: %@", result);
			
}
	

// Handle the response from xGetProjectAddendumc.
		
- (void) xGetProjectAddendumcHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetProjectAddendumc returned the value: %@", result);
			
}
	

// Handle the response from xGetProjectCOList.
		
- (void) xGetProjectCOListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetProjectCOList returned the value: %@", result);
			
}
	

// Handle the response from xGetProjectFiles.
		
- (void) xGetProjectFilesHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetProjectFiles returned the value: %@", result);
			
}
	

// Handle the response from xGetProjectPhotoFolder.
		
- (void) xGetProjectPhotoFolderHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetProjectPhotoFolder returned the value: %@", result);
			
}
	

// Handle the response from xGetProjectRequestedPOLs.
		
- (void) xGetProjectRequestedPOLsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetProjectRequestedPOLs returned the value: %@", result);
			
}
	

// Handle the response from xGetQACalendarCnt.
		
- (void) xGetQACalendarCntHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetQACalendarCnt returned the value: %@", result);
			
}
	

// Handle the response from xGetQACalendarEntry.
		
- (void) xGetQACalendarEntryHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfCalendarQA* result
		wcfCalendarQA* result = (wcfCalendarQA*)value;
	NSLog(@"xGetQACalendarEntry returned the value: %@", result);
			
}
	

// Handle the response from xGetQaCalendarInspection2bItem.
		
- (void) xGetQaCalendarInspection2bItemHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfCalendarQAbItemDetail* result
		wcfCalendarQAbItemDetail* result = (wcfCalendarQAbItemDetail*)value;
	NSLog(@"xGetQaCalendarInspection2bItem returned the value: %@", result);
			
}
	

// Handle the response from xGetQACalendarList.
		
- (void) xGetQACalendarListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetQACalendarList returned the value: %@", result);
			
}
	

// Handle the response from xGetQACalendarStatus.
		
- (void) xGetQACalendarStatusHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xGetQACalendarStatus returned the value: %@", result);
			
}
	

// Handle the response from xGetQAInspection.
		
- (void) xGetQAInspectionHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfInspectionqa* result
		wcfInspectionqa* result = (wcfInspectionqa*)value;
	NSLog(@"xGetQAInspection returned the value: %@", result);
			
}
	

// Handle the response from xGetQAInspection2b.
		
- (void) xGetQAInspection2bHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfCalendarQAb* result
		wcfCalendarQAb* result = (wcfCalendarQAb*)value;
	NSLog(@"xGetQAInspection2b returned the value: %@", result);
			
}
	

// Handle the response from xGetQAInspection2bAdd.
		
- (void) xGetQAInspection2bAddHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetQAInspection2bAdd returned the value: %@", result);
			
}
	

// Handle the response from xGetQAInspection2bItemLs.
		
- (void) xGetQAInspection2bItemLsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetQAInspection2bItemLs returned the value: %@", result);
			
}
	

// Handle the response from xGetReasons.
		
- (void) xGetReasonsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetReasons returned the value: %@", result);
			
}
	

// Handle the response from xGetRequestedPOForApproveDetail.
		
- (void) xGetRequestedPOForApproveDetailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfRequestedPODetail* result
		wcfRequestedPODetail* result = (wcfRequestedPODetail*)value;
	NSLog(@"xGetRequestedPOForApproveDetail returned the value: %@", result);
			
}
	

// Handle the response from xGetRequestedPOForApproveLs.
		
- (void) xGetRequestedPOForApproveLsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetRequestedPOForApproveLs returned the value: %@", result);
			
}
	

// Handle the response from xGetRequestedPOHoldLs.
		
- (void) xGetRequestedPOHoldLsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetRequestedPOHoldLs returned the value: %@", result);
			
}
	

// Handle the response from xgetRequestedPoReason.
		
- (void) xgetRequestedPoReasonHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xgetRequestedPoReason returned the value: %@", result);
			
}
	

// Handle the response from xGetReschedule.
		
- (void) xGetRescheduleHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetReschedule returned the value: %@", result);
			
}
	

// Handle the response from xGetSelectionCalendarCnt.
		
- (void) xGetSelectionCalendarCntHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetSelectionCalendarCnt returned the value: %@", result);
			
}
	

// Handle the response from xGetSelectionCalendarEntry.
		
- (void) xGetSelectionCalendarEntryHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfCalendarEntryItem* result
		wcfCalendarEntryItem* result = (wcfCalendarEntryItem*)value;
	NSLog(@"xGetSelectionCalendarEntry returned the value: %@", result);
			
}
	

// Handle the response from xGetSelectionCalendarList.
		
- (void) xGetSelectionCalendarListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetSelectionCalendarList returned the value: %@", result);
			
}
	

// Handle the response from xGetStartPackList.
		
- (void) xGetStartPackListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetStartPackList returned the value: %@", result);
			
}
	

// Handle the response from xGetSuggestedPrice.
		
- (void) xGetSuggestedPriceHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfSuggestedPriceItem* result
		wcfSuggestedPriceItem* result = (wcfSuggestedPriceItem*)value;
	NSLog(@"xGetSuggestedPrice returned the value: %@", result);
			
}
	

// Handle the response from xGetSuggestedPriceForApprove.
		
- (void) xGetSuggestedPriceForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfSuggestedPriceItem* result
		wcfSuggestedPriceItem* result = (wcfSuggestedPriceItem*)value;
	NSLog(@"xGetSuggestedPriceForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetSuggestedPricelist.
		
- (void) xGetSuggestedPricelistHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetSuggestedPricelist returned the value: %@", result);
			
}
	

// Handle the response from xGetSuggestedPricelistForApprove.
		
- (void) xGetSuggestedPricelistForApproveHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetSuggestedPricelistForApprove returned the value: %@", result);
			
}
	

// Handle the response from xGetTaskDue.
		
- (void) xGetTaskDueHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetTaskDue returned the value: %@", result);
			
}
	

// Handle the response from xGetUserProfile.
		
- (void) xGetUserProfileHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfUserProfileItem* result
		wcfUserProfileItem* result = (wcfUserProfileItem*)value;
	NSLog(@"xGetUserProfile returned the value: %@", result);
			
}
	

// Handle the response from xGetVendorInfo.
		
- (void) xGetVendorInfoHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfVendorInfo* result
		wcfVendorInfo* result = (wcfVendorInfo*)value;
	NSLog(@"xGetVendorInfo returned the value: %@", result);
			
}
	

// Handle the response from xGetVendorInfo2.
		
- (void) xGetVendorInfo2Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfVendorInfo* result
		wcfVendorInfo* result = (wcfVendorInfo*)value;
	NSLog(@"xGetVendorInfo2 returned the value: %@", result);
			
}
	

// Handle the response from xGetVendorPOSelectCia.
		
- (void) xGetVendorPOSelectCiaHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetVendorPOSelectCia returned the value: %@", result);
			
}
	

// Handle the response from xGetVendors.
		
- (void) xGetVendorsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetVendors returned the value: %@", result);
			
}
	

// Handle the response from xHoldRequestedPOWithEmail.
		
- (void) xHoldRequestedPOWithEmailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xHoldRequestedPOWithEmail returned the value: %@", result);
			
}
	

// Handle the response from xisupdate_android.
		
- (void) xisupdate_androidHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xisupdate_android returned the value: %@", result);
			
}
	

// Handle the response from xisupdate_ipad.
		
- (void) xisupdate_ipadHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xisupdate_ipad returned the value: %@", result);
			
}
	

// Handle the response from xisupdate_iphone.
		
- (void) xisupdate_iphoneHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xisupdate_iphone returned the value: %@", result);
			
}
	

// Handle the response from xisupdate_tablet.
		
- (void) xisupdate_tabletHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xisupdate_tablet returned the value: %@", result);
			
}
	

// Handle the response from xNewVPO.
		
- (void) xNewVPOHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xNewVPO returned the value: %@", result);
			
}
	

// Handle the response from xNewVPOWithPhoto.
		
- (void) xNewVPOWithPhotoHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xNewVPOWithPhoto returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bAdd.
		
- (void) xQaCalendarInspection2bAddHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bAdd returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bAddPass.
		
- (void) xQaCalendarInspection2bAddPassHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bAddPass returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bAddPassWithImg.
		
- (void) xQaCalendarInspection2bAddPassWithImgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bAddPassWithImg returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bAddWithImg.
		
- (void) xQaCalendarInspection2bAddWithImgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bAddWithImg returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bBtn3.
		
- (void) xQaCalendarInspection2bBtn3Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bBtn3 returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bBtn3WithImg.
		
- (void) xQaCalendarInspection2bBtn3WithImgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bBtn3WithImg returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bBtn4.
		
- (void) xQaCalendarInspection2bBtn4Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bBtn4 returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bBtn4WithImg.
		
- (void) xQaCalendarInspection2bBtn4WithImgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bBtn4WithImg returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bUpd.
		
- (void) xQaCalendarInspection2bUpdHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bUpd returned the value: %@", result);
			
}
	

// Handle the response from xQaCalendarInspection2bUpdWithImg.
		
- (void) xQaCalendarInspection2bUpdWithImgHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xQaCalendarInspection2bUpdWithImg returned the value: %@", result);
			
}
	

// Handle the response from xSaveSelectionCalendar.
		
- (void) xSaveSelectionCalendarHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xSaveSelectionCalendar returned the value: %@", result);
			
}
	

// Handle the response from xSearchProject.
		
- (void) xSearchProjectHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xSearchProject returned the value: %@", result);
			
}
	

// Handle the response from xSearchProjects.
		
- (void) xSearchProjectsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xSearchProjects returned the value: %@", result);
			
}
	

// Handle the response from xSearchVendorList.
		
- (void) xSearchVendorListHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xSearchVendorList returned the value: %@", result);
			
}
	

// Handle the response from xSendEmail.
		
- (void) xSendEmailHandler: (BOOL) value {
			

	// Do something with the BOOL result
		
	NSLog(@"xSendEmail returned the value: %@", [NSNumber numberWithBool:value]);
			
}
	

// Handle the response from xSendGetPasswordMail.
		
- (void) xSendGetPasswordMailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xSendGetPasswordMail returned the value: %@", result);
			
}
	

// Handle the response from xSendMessage.
		
- (void) xSendMessageHandler: (BOOL) value {
			

	// Do something with the BOOL result
		
	NSLog(@"xSendMessage returned the value: %@", [NSNumber numberWithBool:value]);
			
}
	

// Handle the response from xSubmitReschedule.
		
- (void) xSubmitRescheduleHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xSubmitReschedule returned the value: %@", result);
			
}
	

// Handle the response from xSubmitSuggestPrice.
		
- (void) xSubmitSuggestPriceHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfKeyValueItem* result
		wcfKeyValueItem* result = (wcfKeyValueItem*)value;
	NSLog(@"xSubmitSuggestPrice returned the value: %@", result);
			
}
	

// Handle the response from xUpdateCalendarApprove.
		
- (void) xUpdateCalendarApproveHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"xUpdateCalendarApprove returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from xUpdateCalendarApprove1.
		
- (void) xUpdateCalendarApprove1Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdateCalendarApprove1 returned the value: %@", result);
			
}
	

// Handle the response from xUpdateCalendarDisApprove.
		
- (void) xUpdateCalendarDisApproveHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"xUpdateCalendarDisApprove returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from xUpdateCalendarDisApprove1.
		
- (void) xUpdateCalendarDisApprove1Handler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdateCalendarDisApprove1 returned the value: %@", result);
			
}
	

// Handle the response from xUpdateContract.
		
- (void) xUpdateContractHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"xUpdateContract returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from xUpdateUserChangeOrder.
		
- (void) xUpdateUserChangeOrderHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"xUpdateUserChangeOrder returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from xUpdateUserProfile.
		
- (void) xUpdateUserProfileHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"xUpdateUserProfile returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from xUpdateUserProfileWithoutPhoto.
		
- (void) xUpdateUserProfileWithoutPhotoHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"xUpdateUserProfileWithoutPhoto returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from xUpdateUserPurchaseOrder.
		
- (void) xUpdateUserPurchaseOrderHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"xUpdateUserPurchaseOrder returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from xUpdateVPO.
		
- (void) xUpdateVPOHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdateVPO returned the value: %@", result);
			
}
	

// Handle the response from xUpdateVPOWithPhoto.
		
- (void) xUpdateVPOWithPhotoHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdateVPOWithPhoto returned the value: %@", result);
			
}
	

// Handle the response from xUpdQANotReady.
		
- (void) xUpdQANotReadyHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdQANotReady returned the value: %@", result);
			
}
	

// Handle the response from xUpdQAReady.
		
- (void) xUpdQAReadyHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdQAReady returned the value: %@", result);
			
}
	

// Handle the response from xUpdQAResubmit.
		
- (void) xUpdQAResubmitHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdQAResubmit returned the value: %@", result);
			
}
	

// Handle the response from xUpdQASaveAndFail.
		
- (void) xUpdQASaveAndFailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdQASaveAndFail returned the value: %@", result);
			
}
	

// Handle the response from xUpdQASaveAndFinish.
		
- (void) xUpdQASaveAndFinishHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUpdQASaveAndFinish returned the value: %@", result);
			
}
	

// Handle the response from xUploadPhotos.
		
- (void) xUploadPhotosHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xUploadPhotos returned the value: %@", result);
			
}
	

// Handle the response from xVoidRequestedPOWithEmail.
		
- (void) xVoidRequestedPOWithEmailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xVoidRequestedPOWithEmail returned the value: %@", result);
			
}
	

// Handle the response from xVoidVPO.
		
- (void) xVoidVPOHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xVoidVPO returned the value: %@", result);
			
}
	

@end
		